### ISSUE TITLE
Backend: API for registering new child

### ISSUE THREAD

**Issue by fabrice-niyongabo** [fabrice-niyongabo/child-welfare-portal#10]
This action must be done by both the USER (parent), and ADVISOR.

**Comment by joelkwihangana** [comment]
Still struggling to understand how to use typescript in nodejs!

**Comment by fabrice-niyongabo** [comment]
Will work you through the project. no worries!

**Comment by joelkwihangana** [comment]
**Summary:**
API Endpoint: POST /api/children/register

**Description:** This API registers a new child into the system and notifies the child's parents about the registration.

**Inputs Required:**

**Child Information:**

- First Name
- Last Name
- Age
- Address (District, Province, Cell)
- Gender
- Date of Birth
- BMI (Body Mass Index)
- Weight
- Nutrition Data
- Health Status
- Status (Has Parents or Not)

**Parent Information:**

- Parent's Identification
- Parent's First Name
- Parent's Last Name
- Parent's Contact Information (Phone Number, Email)

**User Information (Umujyanama w'ubuzima):**

- User ID
- User's First Name
- User's Last Name
- User's Role

**Output:**

Upon successful registration, the API returns the child ID.

**Error Handling:**

Handles cases of invalid request format or missing required fields.
Provides appropriate error responses (e.g., 400 Bad Request, 401 Unauthorized).

**Authentication:**

**Requires authentication token (Bearer token) for user authentication.**

**Notes:**

Parent's contact information is optional but recommended for notification purposes.
Input data validation is implemented to ensure data integrity.
The API endpoint follows the RESTful convention for creating resources.
Overall, this API facilitates the process of registering a child into the system, ensuring that both child and parent information are captured accurately, and provides a means of communication by notifying parents about the registration.
